spring:
  application:
    name: biblioteca-api
  
  # Configuração do banco H2 (desenvolvimento)
  datasource:
    url: jdbc:h2:mem:biblioteca
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Console H2 (para visualizar o banco)
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuração do OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    

# Porta do servidor
server:
  port: 8080
